### ISSUE TITLE
Proposal: rename the nodejs/iojs-el WG to nodejs/nodejs-el

### ISSUE THREAD

**Issue by srl295** [nodejs/iojs-el#13]
Dear members of the io.js Greek WG `iojs-el`

It is proposed to rename this repo to:

   [nodejs/nodejs-el](https://github.com/nodejs/nodejs-el/)

As part of the io.js and node.js convergence, node.js releases are now based on the codebase and user base of the converged node.js and io.js communities. A number of the resources and repositories have already been renamed.
In the absence of objections or other discussion, this rename will occur on or after [Oct 28, 2015](http://time.is/1200AM_28_Oct_2015_in_GMT?iojs-rename)

However, active language working groups should take ownership of this issue and discuss/dispose of it according to their own processes.

For more information or to discuss the overall issue, please see and comment on https://github.com/nodejs/node/issues/2525

This statement was authorized by the Node.js TSC

Cc: @nodejs/iojs-el

**Comment by sirodoht** [comment]
Agreed.

I cannot think of any reason not to. Fellow members?

**Comment by kostasx** [comment]
Sure.

**Comment by margaritis** [comment]
I believe we are good to go!

**Comment by AntouanK** [comment]
@srl295 The current website ( https://nodejs.org/en/ ) does not have any of the other language versions.
Are we going to work on translating that new version of the website?

**Comment by srl295** [comment]
@AntouanK great question - see https://github.com/nodejs/new.nodejs.org/issues/222 for the answer: "yes"

**Comment by AntouanK** [comment]
@srl295 Good to know, thanks.

**Comment by srl295** [comment]
Done.

**Comment by margaritis** [comment]
:+1: @srl295
