### ISSUE TITLE
Μετάφραση του 'io.js Week of February 6th 2015'

### ISSUE THREAD

**Issue by sirodoht** [nodejs/iojs-el#2]
Μετάφραση του 'io.js Week of February 6th 2015'

https://medium.com/node-js-javascript/io-js-week-of-february-6th-2015-e185388549a4

Μπορεί να ποσταριστεί σε όποιο social network θεωρείται πιο κατάλληλο. Δεν μου έρχεται κάτι καλύτερο εκτός από Medium.

**Comment by sirodoht** [comment]
https://medium.com/@iojs_el/io-js-6-2015-71156dde5c68

**Comment by AntouanK** [comment]
Το draft του κειμένου → http://goo.gl/fjeP80
